version: '2'
services:
    scsbhipster-app:
        image: scsbhipster
        external_links:
            - scsbhipster-mysql:mysql
            - scsbhipster-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/scsbhipster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    scsbhipster-mysql:
        extends:
            file: mysql.yml
            service: scsbhipster-mysql
    scsbhipster-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: scsbhipster-elasticsearch
